export const LANDING_STATS = {
  LANDING_STATS_FETCH: 'LANDING_STATS_FETCH',
  LANDING_STATS_FETCH_SUCCESS: 'LANDING_STATS_FETCH_SUCCESS',
  LANDING_STATS_FETCH_FAILURE: 'LANDING_STATS_FETCH_FAILURE'
};